/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
import { httpClient } from '../../../shared/api/httpClient';
import type { InterviewQuestionResponse, InterviewQuestionListResponse, ErrorDetail, ErrorBody, ErrorResponse, AddInterviewQuestionResponse, InterviewMessageResponseRole, InterviewMessageResponse, InterviewMessageListResponse, SendInterviewMessageRequest, SendInterviewMessageResponse, StartInterviewResponseStatus, StartInterviewResponse, CoverLetterResponseDisplayStatus, CoverLetterResponse, InterviewSessionResponseStatus, InterviewSessionResponse, CurrentInterviewResponse, Api026Params } from './types';

export const getApi026Url = (interviewSessionId: string,
    params?: Api026Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/interviews/${interviewSessionId}/questions?${stringifiedParams}` : `/interviews/${interviewSessionId}/questions`
}

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 최신 면접 질문부터 cursor 기반으로 조회하고 질문별 대화 진입 정보를 반환한다.
 *
 * ### 사용 화면
 * AI 면접
 *
 * ### 호출 시점
 * 면접 질문 화면 진입, 무한 스크롤 또는 추가 질문 생성 완료 후 호출한다.
 *
 * ### 주요 동작
 * 최초 요청은 cursor를 생략하고 이후 서버가 반환한 nextCursor만 사용한다. size는 1~20이다.
 *
 * ### 성공 후 처리
 * 응답 순서대로 질문을 추가하고 nextCursor=null이면 조회를 종료하며 threadId로 API-029를 연다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 400 | `VALIDATION_ERROR` | cursor 형식 오류 또는 size가 1~20 범위를 벗어남 | 목록 추가를 중단하고 최초 요청 또는 서버가 반환한 nextCursor로 다시 조회한다. |
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | 면접 세션 없음·비소유 또는 삭제된 자기소개서의 세션 | 면접 화면을 종료하고 API-025를 재조회한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-026 · 면접 질문 목록 조회
 */
export const api026 = async (interviewSessionId: string,
    params?: Api026Params, options?: Parameters<typeof httpClient>[1]): Promise<InterviewQuestionListResponse> => {

  return httpClient<InterviewQuestionListResponse>(getApi026Url(interviewSessionId,params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getApi027Url = (interviewSessionId: string,) => {




  return `/interviews/${interviewSessionId}/questions`
}

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 활성 면접 세션에 추가 질문 생성 Job을 시작한다.
 *
 * ### 사용 화면
 * AI 면접
 *
 * ### 호출 시점
 * 사용자가 추가 질문 생성을 요청하거나 실패 후 수동 재시도할 때 호출한다.
 *
 * ### 주요 동작
 * 동일 추가 질문 Job은 기존 jobId를 반환하고 세션 상태·성공 첨삭 버전·다른 AI Job 진행 여부를 검증한다.
 *
 * ### 성공 후 처리
 * jobId로 API-016에 연결하고 COMPLETED이면 API-026을 다시 조회해 새 질문을 반영한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 세션 없음·비소유 또는 삭제된 자기소개서의 세션 | API-025를 재조회한다. |
 * | 409 | `CONFLICT` | 세션이 ACTIVE가 아니거나 성공한 첨삭 버전이 없음 | API-025를 재조회하고 가능한 동작만 활성화한다. |
 * | 409 | `LLM_JOB_ALREADY_RUNNING` | 다른 종류의 AI Job이 진행 중 | 다른 AI 작업 진행을 안내하고 자동 재시도하지 않는다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-027 · 면접 질문 추가 생성
 */
export const api027 = async (interviewSessionId: string, options?: Parameters<typeof httpClient>[1]): Promise<AddInterviewQuestionResponse> => {

  return httpClient<AddInterviewQuestionResponse>(getApi027Url(interviewSessionId),
  {
    ...options,
    method: 'POST'


  }
);}



export const getApi029Url = (threadId: string,) => {




  return `/interview-threads/${threadId}/messages`
}

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 질문별 대화 메시지와 피드백 SSE 복구용 조건부 jobId를 조회한다.
 *
 * ### 사용 화면
 * AI 면접
 *
 * ### 호출 시점
 * 질문 대화 진입, 새로고침 또는 피드백 완료 후 확정 메시지를 조회할 때 호출한다.
 *
 * ### 주요 동작
 * 메시지를 표시 순서로 반환하고 진행·실패 피드백 Job이 있으면 jobId를 함께 반환한다. 실패는 HTTP 오류가 아닌 복구 상태다.
 *
 * ### 성공 후 처리
 * 메시지를 순서대로 표시하고 jobId가 있으면 API-016에 연결한다. 완료 후 다시 조회해 임시 delta를 확정 content·score로 교체한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | thread 없음·비소유 또는 삭제된 자기소개서에 연결됨 | 대화 화면을 종료하고 API-025를 재조회한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-029 · 대화 메시지 조회
 */
export const api029 = async (threadId: string, options?: Parameters<typeof httpClient>[1]): Promise<InterviewMessageListResponse> => {

  return httpClient<InterviewMessageListResponse>(getApi029Url(threadId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getApi023Url = (threadId: string,) => {




  return `/interview-threads/${threadId}/messages`
}

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 사용자 답변을 저장하고 실시간 피드백 생성 Job을 시작한다.
 *
 * ### 사용 화면
 * AI 면접
 *
 * ### 호출 시점
 * 사용자가 면접 답변 입력을 확정해 전송할 때 호출한다.
 *
 * ### 주요 동작
 * 검증된 USER 메시지를 저장하고 userMessageId·jobId를 반환한다. 피드백 delta와 최종 상태는 API-016으로 전달된다.
 *
 * ### 성공 후 처리
 * jobId로 API-016에 연결해 delta를 표시하고 COMPLETED이면 API-029를 다시 조회해 저장된 결과로 교체한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 400 | `VALIDATION_ERROR` | content 누락, trim 후 빈 값 또는 2000자 초과 | 답변 입력란에 details[field=content].reason을 표시한다. |
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | thread 없음·비소유 또는 삭제된 자기소개서에 연결됨 | 대화 화면을 종료하고 API-025를 재조회한다. |
 * | 409 | `LLM_JOB_ALREADY_RUNNING` | 같은 자기소개서에 다른 AI Job이 진행 중 | USER 메시지는 저장되지 않으며 기존 작업 완료 후 다시 전송하도록 안내한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-023 · 사용자 답변 전송
 */
export const api023 = async (threadId: string,
    sendInterviewMessageRequest?: SendInterviewMessageRequest, options?: Parameters<typeof httpClient>[1]): Promise<SendInterviewMessageResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<SendInterviewMessageResponse>(getApi023Url(threadId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(sendInterviewMessageRequest)
  }
);}



export const getApi022Url = (coverLetterId: string,) => {




  return `/cover-letters/${coverLetterId}/interviews`
}

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 최신 성공 첨삭 버전으로 초기 면접 질문 생성 Job을 시작한다.
 *
 * ### 사용 화면
 * AI 면접
 *
 * ### 호출 시점
 * 사용자가 모의면접 시작 또는 초기 질문 생성 실패 후 재시도를 선택할 때 호출한다.
 *
 * ### 주요 동작
 * 동일 초기 질문 Job이 진행 중이면 기존 jobId를 반환하고 다른 AI Job과는 충돌한다.
 *
 * ### 성공 후 처리
 * jobId로 API-016에 연결하고 COMPLETED이면 API-025와 API-026을 다시 조회한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 대상 없음 안내 후 목록으로 이동한다. |
 * | 409 | `CONFLICT` | latestReviewedVersionId가 없어 성공한 첨삭 버전이 없음 | API-012를 재조회해 현재 상태 화면으로 전환한다. |
 * | 409 | `LLM_JOB_ALREADY_RUNNING` | 초기 질문 생성 외 다른 AI Job이 진행 중 | 다른 AI 작업 진행을 안내하고 자동 재시도하지 않는다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-022 · 모의면접 시작
 */
export const api022 = async (coverLetterId: string, options?: Parameters<typeof httpClient>[1]): Promise<StartInterviewResponse> => {

  return httpClient<StartInterviewResponse>(getApi022Url(coverLetterId),
  {
    ...options,
    method: 'POST'


  }
);}



export const getApi025Url = (coverLetterId: string,) => {




  return `/cover-letters/${coverLetterId}/interview`
}

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 자기소개서 요약, 현재 면접 세션과 미해결 질문 생성 Job을 조회한다.
 *
 * ### 사용 화면
 * AI 면접
 *
 * ### 호출 시점
 * 면접 화면 진입·새로고침 또는 SSE 상태 복구 시 호출한다.
 *
 * ### 주요 동작
 * 세션 없음과 FAILED도 200 정상 응답이며 진행 중 초기·추가 질문 생성이 있으면 조건부 jobId를 반환한다.
 *
 * ### 성공 후 처리
 * jobId가 있으면 API-016에 연결하고 ACTIVE이면 기존 질문·대화 화면을 표시한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 대상 없음 안내 후 목록으로 이동한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-025 · 현재 면접 세션 조회
 */
export const api025 = async (coverLetterId: string, options?: Parameters<typeof httpClient>[1]): Promise<CurrentInterviewResponse> => {

  return httpClient<CurrentInterviewResponse>(getApi025Url(coverLetterId),
  {
    ...options,
    method: 'GET'


  }
);}
