/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
export interface InterviewQuestionResponse {
  id: string;
  order: number;
  question: string;
  threadId: string;
}

export interface InterviewQuestionListResponse {
  items: InterviewQuestionResponse[];
  /** @nullable */
  nextCursor: string | null;
}

export interface ErrorDetail {
  field: string;
  reason: string;
}

export interface ErrorBody {
  code: string;
  message: string;
  details: ErrorDetail[];
}

export interface ErrorResponse {
  error: ErrorBody;
}

export interface AddInterviewQuestionResponse {
  jobId: string;
}

export type InterviewMessageResponseRole = typeof InterviewMessageResponseRole[keyof typeof InterviewMessageResponseRole];


export const InterviewMessageResponseRole = {
  USER: 'USER',
  ASSISTANT: 'ASSISTANT',
} as const;

export interface InterviewMessageResponse {
  id: string;
  role: InterviewMessageResponseRole;
  content: string;
  /** @nullable */
  score: number | null;
  createdAt: string;
}

export interface InterviewMessageListResponse {
  /** @nullable */
  jobId: string | null;
  items: InterviewMessageResponse[];
}

export interface SendInterviewMessageRequest {
  /**
     * 면접 질문에 대한 사용자 답변. trim 후 1자 이상 2000자 이하
     * @minLength 1
     * @maxLength 2000
     */
  content: string;
}

export interface SendInterviewMessageResponse {
  userMessageId: string;
  jobId: string;
}

export type StartInterviewResponseStatus = typeof StartInterviewResponseStatus[keyof typeof StartInterviewResponseStatus];


export const StartInterviewResponseStatus = {
  QUESTION_GENERATING: 'QUESTION_GENERATING',
  ACTIVE: 'ACTIVE',
  FAILED: 'FAILED',
} as const;

export interface StartInterviewResponse {
  interviewSessionId: string;
  /** @nullable */
  jobId: string | null;
  status: StartInterviewResponseStatus;
}

export interface CurrentInterviewCoverLetterResponse {
  id: string;
  /** @nullable */
  title: string | null;
  /** @nullable */
  companyName: string | null;
  /** @nullable */
  positionTitle: string | null;
}

export type InterviewSessionResponseStatus = typeof InterviewSessionResponseStatus[keyof typeof InterviewSessionResponseStatus];


export const InterviewSessionResponseStatus = {
  QUESTION_GENERATING: 'QUESTION_GENERATING',
  ACTIVE: 'ACTIVE',
  FAILED: 'FAILED',
} as const;

export interface InterviewSessionResponse {
  id: string;
  initialSourceReviewVersionId: string;
  status: InterviewSessionResponseStatus;
  /** @nullable */
  jobId: string | null;
  createdAt: string;
}

export interface CurrentInterviewResponse {
  coverLetter: CurrentInterviewCoverLetterResponse;
  interviewSession: InterviewSessionResponse | null;
}

export type ListInterviewQuestionsParams = {
cursor?: string;
size?: number;
};
