/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
import { httpClient } from '@/shared/api/httpClient';
import type { SuccessResponse, ErrorDetail, ErrorBody, ErrorResponse, CurrentUserResponse, CsrfTokenResponse, HandleKakaoCallbackParams, StartKakaoLoginParams, StartKakaoLoginTarget } from './types';

export const getRefreshAuthTokensUrl = () => {




  return `/auth/refresh`
}

/**
 * > 인증: 불필요 · CSRF: 필요
 *
 * ### 사용 목적
 * refresh token을 원자적으로 회전하고 새 인증 Cookie를 발급한다.
 *
 * ### 사용 화면
 * 로그인
 *
 * ### 호출 시점
 * 보호 API의 401을 감지했을 때 여러 요청을 single-flight로 묶어 한 번 호출한다.
 *
 * ### 주요 동작
 * 기존 refresh token을 폐기하고 access_token·refresh_token Cookie를 함께 교체한다. 로그아웃 흐름과 직렬화한다.
 *
 * ### 성공 후 처리
 * 대기 중인 원 요청을 각각 한 번만 재시도한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | refresh token 누락·만료·위조·폐기·재사용 | 인증 상태를 정리하고 로그인 화면으로 이동하며 refresh를 반복하지 않는다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-004 · 토큰 갱신
 */
export const refreshAuthTokens = async ( options?: Parameters<typeof httpClient>[1]): Promise<SuccessResponse> => {

  return httpClient<SuccessResponse>(getRefreshAuthTokensUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getLogoutUrl = () => {




  return `/auth/logout`
}

/**
 * > 인증: 불필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 유효한 refresh token을 폐기하고 인증 Cookie를 만료한다.
 *
 * ### 사용 화면
 * 로그인
 *
 * ### 호출 시점
 * 사용자가 로그아웃을 확정할 때 진행 중인 refresh 흐름과 직렬화해 호출한다.
 *
 * ### 주요 동작
 * 인증 Cookie가 없거나 만료되어도 멱등하게 성공하며 access_token과 refresh_token Cookie를 모두 만료한다.
 *
 * ### 성공 후 처리
 * 프론트엔드 사용자 상태를 비우고 로그인 화면으로 이동한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-006 · 로그아웃
 */
export const logout = async ( options?: Parameters<typeof httpClient>[1]): Promise<SuccessResponse> => {

  return httpClient<SuccessResponse>(getLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getGetCurrentUserUrl = () => {




  return `/user/me`
}

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 현재 access token으로 로그인한 사용자의 앱 사용자 정보를 조회한다.
 *
 * ### 사용 화면
 * 로그인
 *
 * ### 호출 시점
 * 앱 초기 진입이나 인증 상태 복구 후 사용자 상태를 구성할 때 호출한다.
 *
 * ### 주요 동작
 * 현재 인증 사용자만 조회하며 별도 도메인 오류는 없다.
 *
 * ### 성공 후 처리
 * 사용자 상태를 구성하고 인증이 필요한 화면을 표시한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-005 · 내 정보 조회
 */
export const getCurrentUser = async ( options?: Parameters<typeof httpClient>[1]): Promise<CurrentUserResponse> => {

  return httpClient<CurrentUserResponse>(getGetCurrentUserUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getHandleKakaoCallbackUrl = (params?: HandleKakaoCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/kakao/callback?${stringifiedParams}` : `/auth/kakao/callback`
}

/**
 * > 인증: 불필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 카카오 인가 결과를 검증하고 성공 시 Rewrite 인증 Cookie를 발급한다.
 *
 * ### 사용 화면
 * 로그인
 *
 * ### 호출 시점
 * 카카오가 로그인·동의 처리 후 브라우저를 callback으로 돌려보낼 때 호출된다.
 *
 * ### 주요 동작
 * 프론트엔드가 직접 호출하지 않는 브라우저 redirect endpoint다. state와 nonce를 일회성으로 검증하고 state에 결합된 local 또는 production 목적지를 선택하며 모든 결과에서 nonce Cookie를 만료한다.
 *
 * ### 성공 후 처리
 * 302로 앱에 이동하며 access_token과 refresh_token HttpOnly Cookie를 발급한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 302 | `KAKAO_LOGIN_CANCELED` | 사용자가 카카오 로그인 또는 동의를 취소함 | 취소 안내를 표시하고 로그인 버튼을 다시 활성화한다. |
 * | 302 | `KAKAO_LOGIN_FAILED` | state·nonce 검증, code 교환, 사용자 조회 또는 저장 실패 | 일반 로그인 실패 안내를 표시하고 내부 원인은 노출하지 않으며 자동 재시도하지 않는다. |
 * @summary API-002 · 카카오 OAuth callback
 */
export const handleKakaoCallback = async (params?: HandleKakaoCallbackParams, options?: Parameters<typeof httpClient>[1]): Promise<unknown> => {

  return httpClient<unknown>(getHandleKakaoCallbackUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getStartKakaoLoginUrl = (params?: StartKakaoLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/kakao/authorize?${stringifiedParams}` : `/auth/kakao/authorize`
}

/**
 * > 인증: 불필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 카카오 OAuth 인가를 시작하고 요청 브라우저 검증용 nonce Cookie를 발급한다.
 *
 * ### 사용 화면
 * 로그인
 *
 * ### 호출 시점
 * 사용자가 카카오 로그인 버튼을 누를 때 브라우저를 이 endpoint로 이동시킨다.
 *
 * ### 주요 동작
 * JSON 호출이 아니라 302 redirect 흐름이다. target은 local 또는 production만 허용하고 OAuth state에 결합한다. oauth_login_nonce Cookie는 HttpOnly로 발급하며 프론트엔드가 읽지 않는다.
 *
 * ### 성공 후 처리
 * 302 Location의 카카오 인가 화면으로 이동하고 로그인 버튼 중복 클릭을 막는다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 302 | `KAKAO_LOGIN_FAILED` | 카카오 인가 URL 생성 등 로그인 시작 처리 실패 | 로그인 화면에서 일반 실패 안내를 표시하고 버튼을 다시 활성화하며 자동 재시도하지 않는다. |
 * @summary API-001 · 카카오 로그인 시작
 */
export const startKakaoLogin = async (params?: StartKakaoLoginParams, options?: Parameters<typeof httpClient>[1]): Promise<unknown> => {

  return httpClient<unknown>(getStartKakaoLoginUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetCsrfTokenUrl = () => {




  return `/auth/csrf-token`
}

/**
 * > 인증: 불필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 상태 변경 요청의 X-CSRF-Token 헤더에 사용할 토큰을 인증 없이 발급한다.
 *
 * ### 사용 화면
 * 공통, 로그인
 *
 * ### 호출 시점
 * 앱 초기화 또는 CSRF_TOKEN_INVALID 복구 시 호출한다.
 *
 * ### 주요 동작
 * 토큰은 브라우저 메모리에 보관하고 POST·PUT·PATCH·DELETE 요청 헤더에 사용한다.
 *
 * ### 성공 후 처리
 * 발급 토큰을 메모리에 교체하고 대기 중인 상태 변경 요청을 진행한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-003 · CSRF 토큰 조회
 */
export const getCsrfToken = async ( options?: Parameters<typeof httpClient>[1]): Promise<CsrfTokenResponse> => {

  return httpClient<CsrfTokenResponse>(getGetCsrfTokenUrl(),
  {
    ...options,
    method: 'GET'


  }
);}
