/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
export interface SuccessResponse {
  success: boolean;
}

export interface ErrorDetail {
  field: string;
  reason: string;
}

export interface ErrorBody {
  code: string;
  message: string;
  details: ErrorDetail[];
}

export interface ErrorResponse {
  error: ErrorBody;
}

export interface CurrentUserResponse {
  id: string;
  nickname: string;
  /** @nullable */
  profileImageUrl: string | null;
  provider: string;
  createdAt: string;
}

export interface CsrfTokenResponse {
  csrfToken: string;
}

export type HandleKakaoCallbackParams = {
code?: string;
error?: string;
state?: string;
};

export type StartKakaoLoginParams = {
/**
 * 로그인 완료 후 이동할 프론트엔드 환경
 */
target?: StartKakaoLoginTarget;
};

export type StartKakaoLoginTarget = typeof StartKakaoLoginTarget[keyof typeof StartKakaoLoginTarget];


export const StartKakaoLoginTarget = {
  local: 'local',
  production: 'production',
} as const;
