/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
import { httpClient } from '@/shared/api/httpClient';
import type {
  StartKeywordAnalysisResponseStatus,
  StartKeywordAnalysisResponse,
  ErrorDetail,
  ErrorBody,
  ErrorResponse,
  KeywordAnalysisCoverLetterResponse,
  KeywordAnalysisReviewVersionResponse,
  KeywordResponse,
  LatestKeywordAnalysisResponse,
} from './types';

export const getStartKeywordAnalysisUrl = (coverLetterId: string) => {
  return `/cover-letters/${coverLetterId}/keyword-analysis`;
};

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 최신 성공 첨삭 버전으로 키워드 분석 Job을 시작한다.
 *
 * ### 사용 화면
 * 키워드 분석
 *
 * ### 호출 시점
 * 사용자가 키워드 분석을 처음 시작하거나 실패 후 재분석할 때 호출한다.
 *
 * ### 주요 동작
 * 동일 키워드 분석 Job이 진행 중이면 기존 jobId를 반환하고 다른 종류의 AI Job과는 충돌한다.
 *
 * ### 성공 후 처리
 * jobId로 API-016에 연결하고 COMPLETED이면 API-021을 다시 조회한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 대상 없음 안내 후 목록으로 이동한다. |
 * | 409 | `CONFLICT` | latestReviewedVersionId가 없어 성공한 첨삭 버전이 없음 | API-012를 재조회해 현재 상태 화면으로 전환한다. |
 * | 409 | `LLM_JOB_ALREADY_RUNNING` | 키워드 분석 외 다른 AI Job이 진행 중 | 다른 AI 작업 진행을 안내하고 자동 재시도하지 않는다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-020 · 키워드 분석 시작 또는 재분석
 */
export const startKeywordAnalysis = async (
  coverLetterId: string,
  options?: Parameters<typeof httpClient>[1]
): Promise<StartKeywordAnalysisResponse> => {
  return httpClient<StartKeywordAnalysisResponse>(getStartKeywordAnalysisUrl(coverLetterId), {
    ...options,
    method: 'POST',
  });
};

export const getGetLatestKeywordAnalysisUrl = (coverLetterId: string) => {
  return `/cover-letters/${coverLetterId}/keyword-analysis/latest`;
};

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 키워드 분석 화면 데이터와 SSE 복구용 조건부 jobId를 조회한다.
 *
 * ### 사용 화면
 * 키워드 분석
 *
 * ### 호출 시점
 * 화면 진입·새로고침 또는 API-016 연결 실패 중 polling할 때 호출한다.
 *
 * ### 주요 동작
 * NOT_STARTED·PROCESSING·COMPLETED·FAILED를 모두 200 정상 상태로 반환하고 PROCESSING일 때 jobId를 제공한다.
 *
 * ### 성공 후 처리
 * PROCESSING이면 API-016에 연결하고 COMPLETED이면 결과를 표시하며 FAILED이면 API-020 재시도를 제공한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 대상 없음 안내 후 목록으로 이동한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-021 · 최신 키워드 분석 조회
 */
export const getLatestKeywordAnalysis = async (
  coverLetterId: string,
  options?: Parameters<typeof httpClient>[1]
): Promise<LatestKeywordAnalysisResponse> => {
  return httpClient<LatestKeywordAnalysisResponse>(getGetLatestKeywordAnalysisUrl(coverLetterId), {
    ...options,
    method: 'GET',
  });
};
