/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
export type StartKeywordAnalysisResponseStatus = typeof StartKeywordAnalysisResponseStatus[keyof typeof StartKeywordAnalysisResponseStatus];


export const StartKeywordAnalysisResponseStatus = {
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;

export interface StartKeywordAnalysisResponse {
  status?: StartKeywordAnalysisResponseStatus;
  jobId?: string;
}

export interface ErrorDetail {
  field?: string;
  reason?: string;
}

export interface ErrorBody {
  code?: string;
  message?: string;
  details?: ErrorDetail[];
}

export interface ErrorResponse {
  error?: ErrorBody;
}

export type CoverLetterResponseDisplayStatus = typeof CoverLetterResponseDisplayStatus[keyof typeof CoverLetterResponseDisplayStatus];


export const CoverLetterResponseDisplayStatus = {
  WRITING: 'WRITING',
  REVIEWING: 'REVIEWING',
  REVIEWED: 'REVIEWED',
  REVIEW_FAILED: 'REVIEW_FAILED',
} as const;

export interface CoverLetterResponse {
  id?: string;
  title?: string;
  companyName?: string;
  positionTitle?: string;
  jobPostingUrl?: string;
  preferences?: string;
  displayStatus?: CoverLetterResponseDisplayStatus;
}

export interface ReviewVersionResponse {
  id?: string;
  version?: string;
  isLatest?: boolean;
  requestInstruction?: string;
  createdAt?: string;
}

export interface KeywordResponse {
  keyword?: string;
  importance?: number;
}

export interface LatestKeywordAnalysisResponse {
  coverLetter?: CoverLetterResponse;
  sourceReviewVersion?: ReviewVersionResponse;
  status?: string;
  jobId?: string;
  keywords?: KeywordResponse[];
}
