/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
export type StartKeywordAnalysisResponseStatus =
  (typeof StartKeywordAnalysisResponseStatus)[keyof typeof StartKeywordAnalysisResponseStatus];

export const StartKeywordAnalysisResponseStatus = {
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;

export interface StartKeywordAnalysisResponse {
  status: StartKeywordAnalysisResponseStatus;
  jobId: string;
}

export interface ErrorDetail {
  field: string;
  reason: string;
}

export interface ErrorBody {
  code: string;
  message: string;
  details: ErrorDetail[];
}

export interface ErrorResponse {
  error: ErrorBody;
}

export interface KeywordAnalysisCoverLetterResponse {
  id: string;
  /** @nullable */
  title: string | null;
  /** @nullable */
  companyName: string | null;
  /** @nullable */
  positionTitle: string | null;
}

export interface KeywordAnalysisReviewVersionResponse {
  id: string;
  version: string;
}

export interface KeywordResponse {
  keyword: string;
  importance: number;
}

export interface LatestKeywordAnalysisResponse {
  coverLetter: KeywordAnalysisCoverLetterResponse;
  sourceReviewVersion: KeywordAnalysisReviewVersionResponse | null;
  status: string;
  /** @nullable */
  jobId: string | null;
  keywords: KeywordResponse[];
}
