/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
import { httpClient } from '@/shared/api/httpClient';
import type { AnswerRequest, SaveFinalAnswersRequest, SuccessResponse, ErrorDetail, ErrorBody, ErrorResponse, ReviewVersionListItemResponse, ReviewVersionListResponse, RequestReReviewRequest, RequestReReviewResponseDisplayStatus, RequestReReviewResponse, CoverLetterDetailCoverLetterResponseDisplayStatus, CoverLetterDetailCoverLetterResponse, CoverLetterDetailReviewVersionResponse, ReviewJobResponseStatus, CoverLetterDetailProgressResponse, CoverLetterDetailJobErrorResponse, ReviewJobResponse, QuestionResponse, CoverLetterDetailResponse } from './types';

export const getSaveFinalAnswersUrl = (coverLetterId: string,
    versionId: string,) => {




  return `/cover-letters/${coverLetterId}/review-versions/${versionId}/final-answers`
}

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 최신 첨삭 버전의 모든 문항 최종 작성본을 한 번에 저장한다.
 *
 * ### 사용 화면
 * 첨삭 결과
 *
 * ### 호출 시점
 * 사용자가 최신 버전의 최종 작성본 편집을 저장할 때 호출한다.
 *
 * ### 주요 동작
 * 모든 문항 포함·중복·소속·빈 값·길이를 검증하고 최신 버전에만 전체 replace로 저장한다.
 *
 * ### 성공 후 처리
 * 로컬 입력을 유지하고 서버 정규화 값을 다시 맞출 필요가 있으면 API-012 또는 API-018을 조회한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 400 | `VALIDATION_ERROR` | 문항 누락·중복·불일치, 빈 답변 또는 길이 위반 | details[].field를 문항 입력이나 전체 answers 오류에 연결한다. |
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 자기소개서·버전 없음, 비소유·삭제 | 입력값을 유지하고 대상 없음 안내 후 이전 화면으로 이동한다. |
 * | 409 | `REVIEW_VERSION_NOT_LATEST` | 열린 버전이 더 이상 최신 버전이 아님 | 자동 재전송하지 않고 API-012 또는 API-018로 최신 데이터를 조회한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-019 · 최종 작성본 일괄 저장
 */
export const saveFinalAnswers = async (coverLetterId: string,
    versionId: string,
    saveFinalAnswersRequest: SaveFinalAnswersRequest, options?: Parameters<typeof httpClient>[1]): Promise<SuccessResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<SuccessResponse>(getSaveFinalAnswersUrl(coverLetterId,versionId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(saveFinalAnswersRequest)
  }
);}



export const getListReviewVersionsUrl = (coverLetterId: string,) => {




  return `/cover-letters/${coverLetterId}/review-versions`
}

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 자기소개서의 성공한 첨삭 버전 목록을 과거부터 최신 순으로 조회한다.
 *
 * ### 사용 화면
 * 첨삭 결과
 *
 * ### 호출 시점
 * 첨삭 결과 화면에서 버전 선택 목록을 구성하거나 완료 후 목록을 갱신할 때 호출한다.
 *
 * ### 주요 동작
 * 성공한 버전만 반환하며 isLatest로 최신 버전의 편집 가능 여부를 구분한다. 성공 버전이 없으면 빈 배열이다.
 *
 * ### 성공 후 처리
 * 선택한 versionId로 API-018을 조회하고 isLatest 버전에만 최종 작성본 편집을 제공한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 대상 없음 안내 후 자기소개서 목록으로 이동한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-017 · 첨삭 버전 목록 조회
 */
export const listReviewVersions = async (coverLetterId: string, options?: Parameters<typeof httpClient>[1]): Promise<ReviewVersionListResponse> => {

  return httpClient<ReviewVersionListResponse>(getListReviewVersionsUrl(coverLetterId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getRequestReReviewUrl = (coverLetterId: string,) => {




  return `/cover-letters/${coverLetterId}/review-versions`
}

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 최신 성공 버전의 최종 작성본을 기준으로 재첨삭 Job을 시작한다.
 *
 * ### 사용 화면
 * 첨삭 결과, 첨삭 진행
 *
 * ### 호출 시점
 * 사용자가 재첨삭 요구사항을 확인하고 다시 첨삭받기를 요청할 때 호출한다.
 *
 * ### 주요 동작
 * 동일 재첨삭 Job이 진행 중이면 기존 jobId를 반환한다. Job 시작 후 AI 실패는 API-016·015의 FAILED 상태로 전달된다.
 *
 * ### 성공 후 처리
 * displayStatus=REVIEWING을 반영하고 jobId로 API-016에 연결한다. 완료 후 API-017과 상세를 다시 조회한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 400 | `VALIDATION_ERROR` | requestInstruction이 1000자 초과 | 입력란에 details[].reason을 표시한다. |
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 대상 없음 안내 후 목록으로 이동한다. |
 * | 409 | `CONFLICT` | latestReviewedVersionId가 없어 최신 성공 버전이 없음 | API-012를 재조회해 현재 상태 화면으로 전환한다. |
 * | 409 | `LLM_JOB_ALREADY_RUNNING` | 재첨삭 외 다른 AI Job이 진행 중 | 다른 AI 작업이 진행 중임을 안내하고 요청을 중단한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-024 · AI 첨삭 다시받기
 */
export const requestReReview = async (coverLetterId: string,
    requestReReviewRequest?: RequestReReviewRequest, options?: Parameters<typeof httpClient>[1]): Promise<RequestReReviewResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<RequestReReviewResponse>(getRequestReReviewUrl(coverLetterId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(requestReReviewRequest)
  }
);}



export const getGetReviewVersionDetailUrl = (coverLetterId: string,
    versionId: string,) => {




  return `/cover-letters/${coverLetterId}/review-versions/${versionId}`
}

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 선택한 성공 첨삭 버전의 자기소개서와 문항별 결과를 조회한다.
 *
 * ### 사용 화면
 * 첨삭 결과
 *
 * ### 호출 시점
 * 사용자가 API-017 버전 목록에서 특정 버전을 선택할 때 호출한다.
 *
 * ### 주요 동작
 * 선택 버전의 aiReport·rewrittenAnswer·finalAnswer와 길이 필드를 공통 상세 구조로 반환한다.
 *
 * ### 성공 후 처리
 * 문항을 order로 정렬해 표시하고 최신 버전 여부에 따라 최종 작성본 편집을 제어한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | 자기소개서·첨삭 버전 없음, 비소유·삭제 또는 버전 소속 불일치 | 버전 목록 또는 자기소개서 목록으로 이동한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-018 · 첨삭 버전 상세 조회
 */
export const getReviewVersionDetail = async (coverLetterId: string,
    versionId: string, options?: Parameters<typeof httpClient>[1]): Promise<CoverLetterDetailResponse> => {

  return httpClient<CoverLetterDetailResponse>(getGetReviewVersionDetailUrl(coverLetterId,versionId),
  {
    ...options,
    method: 'GET'


  }
);}
