/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
export interface AnswerRequest {
  /** 저장할 첨삭 문항 결과 ID */
  questionResultId: string;
  /**
     * 최종 작성본. trim 후 1자 이상 5000자 이하
     * @minLength 1
     * @maxLength 5000
     */
  finalAnswer: string;
}

export interface SaveFinalAnswersRequest {
  /** 첨삭 버전에 포함된 모든 문항의 최종 작성본 */
  answers: AnswerRequest[];
}

export interface SuccessResponse {
  success?: boolean;
}

export interface ErrorDetail {
  field?: string;
  reason?: string;
}

export interface ErrorBody {
  code?: string;
  message?: string;
  details?: ErrorDetail[];
}

export interface ErrorResponse {
  error?: ErrorBody;
}

export interface ReviewVersionListItemResponse {
  id?: string;
  version?: string;
  isLatest?: boolean;
  createdAt?: string;
}

export interface ReviewVersionListResponse {
  items?: ReviewVersionListItemResponse[];
}

export interface RequestReReviewRequest {
  /**
     * 재첨삭 요구사항. 값이 있으면 trim 후 최대 1000자
     * @maxLength 1000
     * @nullable
     */
  requestInstruction?: string | null;
}

export type RequestReReviewResponseDisplayStatus = typeof RequestReReviewResponseDisplayStatus[keyof typeof RequestReReviewResponseDisplayStatus];


export const RequestReReviewResponseDisplayStatus = {
  WRITING: 'WRITING',
  REVIEWING: 'REVIEWING',
  REVIEWED: 'REVIEWED',
  REVIEW_FAILED: 'REVIEW_FAILED',
} as const;

export interface RequestReReviewResponse {
  displayStatus?: RequestReReviewResponseDisplayStatus;
  jobId?: string;
}

export type CoverLetterResponseDisplayStatus = typeof CoverLetterResponseDisplayStatus[keyof typeof CoverLetterResponseDisplayStatus];


export const CoverLetterResponseDisplayStatus = {
  WRITING: 'WRITING',
  REVIEWING: 'REVIEWING',
  REVIEWED: 'REVIEWED',
  REVIEW_FAILED: 'REVIEW_FAILED',
} as const;

export interface CoverLetterResponse {
  id?: string;
  title?: string;
  companyName?: string;
  positionTitle?: string;
  jobPostingUrl?: string;
  preferences?: string;
  displayStatus?: CoverLetterResponseDisplayStatus;
}

export interface ReviewVersionResponse {
  id?: string;
  version?: string;
  isLatest?: boolean;
  requestInstruction?: string;
  createdAt?: string;
}

export type ReviewJobResponseStatus = typeof ReviewJobResponseStatus[keyof typeof ReviewJobResponseStatus];


export const ReviewJobResponseStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
} as const;

export interface ProgressResponse {
  current?: number;
  total?: number;
  message?: string;
}

export interface ReviewJobResponse {
  id?: string;
  status?: ReviewJobResponseStatus;
  progress?: ProgressResponse;
  error?: ErrorResponse;
}

export interface QuestionResponse {
  questionResultId?: string;
  questionId?: string;
  order?: number;
  question?: string;
  maxAnswerLength?: number;
  originalAnswer?: string;
  originalAnswerLength?: number;
  aiReport?: string;
  rewrittenAnswer?: string;
  rewrittenAnswerLength?: number;
  finalAnswer?: string;
  finalAnswerLength?: number;
}

export interface CoverLetterDetailResponse {
  coverLetter?: CoverLetterResponse;
  reviewVersion?: ReviewVersionResponse;
  reviewJob?: ReviewJobResponse;
  questions?: QuestionResponse[];
}
