/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
import { httpClient } from '@/shared/api/httpClient';
import type {
  QuestionRequest,
  SaveQuestionsRequest,
  SuccessResponse,
  ErrorDetail,
  ErrorBody,
  ErrorResponse,
  SavePreferencesRequest,
  SaveBasicInfoRequest,
  CoverLetterListItemResponseDisplayStatus,
  CoverLetterListItemResponse,
  CoverLetterListResponse,
  CreateCoverLetterResponse,
  SubmitCoverLetterResponseDisplayStatus,
  SubmitCoverLetterResponse,
  CoverLetterDetailCoverLetterResponseDisplayStatus,
  CoverLetterDetailCoverLetterResponse,
  CoverLetterDetailReviewVersionResponse,
  ReviewJobResponseStatus,
  CoverLetterDetailProgressResponse,
  CoverLetterDetailJobErrorResponse,
  ReviewJobResponse,
  QuestionResponse,
  CoverLetterDetailResponse,
  ListCoverLettersParams,
} from './types';

export const getSaveCoverLetterQuestionsUrl = (coverLetterId: string) => {
  return `/cover-letters/${coverLetterId}/questions`;
};

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 자기소개서 등록 3단계의 미완성 질문과 답변을 임시저장한다.
 *
 * ### 사용 화면
 * 자기소개서 등록
 *
 * ### 호출 시점
 * 문항 입력 변경 후 자동 저장할 때 호출한다.
 *
 * ### 주요 동작
 * 현재 문항 배열 전체를 순서대로 WRITING 스냅샷으로 교체하며 nullable 입력은 제출 전까지 허용한다.
 *
 * ### 성공 후 처리
 * 임시저장 완료로 처리하고 제출 가능 여부는 프론트엔드가 현재 입력값으로 판단한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 400 | `VALIDATION_ERROR` | null 문항 객체 또는 문항 필드 길이·범위 위반 | questions[index].field를 해당 문항 입력에 연결한다. |
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 자동저장을 중단하고 목록으로 이동한다. |
 * | 409 | `COVER_LETTER_NOT_WRITING` | 자기소개서가 WRITING 상태가 아님 | 대기 중 자동저장을 폐기하고 API-012를 재조회한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-011 · 질문과 답변 저장
 */
export const saveCoverLetterQuestions = async (
  coverLetterId: string,
  saveQuestionsRequest: SaveQuestionsRequest,
  options?: Parameters<typeof httpClient>[1]
): Promise<SuccessResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string]
        )
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return httpClient<SuccessResponse>(getSaveCoverLetterQuestionsUrl(coverLetterId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(saveQuestionsRequest),
  });
};

export const getSaveCoverLetterPreferencesUrl = (coverLetterId: string) => {
  return `/cover-letters/${coverLetterId}/preferences`;
};

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 자기소개서 등록 2단계의 미완성 우대사항을 임시저장한다.
 *
 * ### 사용 화면
 * 자기소개서 등록
 *
 * ### 호출 시점
 * 우대사항 입력 변경 후 자동 저장할 때 호출한다.
 *
 * ### 주요 동작
 * 현재 입력 전체를 WRITING 스냅샷으로 교체하고 누락·null·빈 문자열은 null로 정규화한다.
 *
 * ### 성공 후 처리
 * 임시저장 완료로 처리하며 다음 단계 이동 여부는 프론트엔드가 판단한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 400 | `VALIDATION_ERROR` | preferences 최대 3000자 위반 | 해당 입력에 details[].reason을 표시한다. |
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 자동저장을 중단하고 목록으로 이동한다. |
 * | 409 | `COVER_LETTER_NOT_WRITING` | 자기소개서가 WRITING 상태가 아님 | 대기 중 자동저장을 폐기하고 API-012를 재조회한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-010 · 채용 우대사항 저장
 */
export const saveCoverLetterPreferences = async (
  coverLetterId: string,
  savePreferencesRequest: SavePreferencesRequest,
  options?: Parameters<typeof httpClient>[1]
): Promise<SuccessResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string]
        )
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return httpClient<SuccessResponse>(getSaveCoverLetterPreferencesUrl(coverLetterId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(savePreferencesRequest),
  });
};

export const getSaveCoverLetterBasicInfoUrl = (coverLetterId: string) => {
  return `/cover-letters/${coverLetterId}/basic-info`;
};

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 자기소개서 등록 1단계의 미완성 기본 정보를 임시저장한다.
 *
 * ### 사용 화면
 * 자기소개서 등록
 *
 * ### 호출 시점
 * 기본 정보 입력 변경 후 자동 저장할 때 호출한다.
 *
 * ### 주요 동작
 * 현재 폼 전체를 WRITING 스냅샷으로 교체 저장한다.
 * 누락·null·trim 후 빈 문자열은 null로 정규화하고, 값이 있는 필드만 길이와 URL 형식을 검증한다.
 *
 *
 * ### 성공 후 처리
 * 임시저장 완료로 처리하며 다음 단계 이동 여부는 프론트엔드가 현재 입력값으로 판단한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 400 | `VALIDATION_ERROR` | 입력된 기본 정보의 최대 길이 또는 URL 형식 위반 | details[].field와 reason을 해당 입력에 표시한다. |
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 자동저장을 중단하고 목록으로 이동한다. |
 * | 409 | `COVER_LETTER_NOT_WRITING` | 자기소개서가 WRITING 상태가 아님 | 대기 중 자동저장을 폐기하고 API-012를 재조회해 현재 상태 화면으로 전환한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-009 · 기본 정보 저장
 */
export const saveCoverLetterBasicInfo = async (
  coverLetterId: string,
  saveBasicInfoRequest: SaveBasicInfoRequest,
  options?: Parameters<typeof httpClient>[1]
): Promise<SuccessResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string]
        )
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return httpClient<SuccessResponse>(getSaveCoverLetterBasicInfoUrl(coverLetterId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(saveBasicInfoRequest),
  });
};

export const getListCoverLettersUrl = (params?: ListCoverLettersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/cover-letters?${stringifiedParams}` : `/cover-letters`;
};

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 현재 사용자의 모든 상태 자기소개서를 페이지 단위로 조회한다.
 *
 * ### 사용 화면
 * 자기소개서 목록
 *
 * ### 호출 시점
 * 목록 화면 진입, 페이지 이동 또는 상태 복구가 필요할 때 호출한다.
 *
 * ### 주요 동작
 * page는 1부터 시작하고 size는 1~9다. 저장된 상태를 displayStatus로 반환하며 전체 페이지를 넘으면 빈 목록이다.
 *
 * ### 성공 후 처리
 * displayStatus에 따라 작성·진행·완료·실패 카드를 표시한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 400 | `VALIDATION_ERROR` | page < 1 또는 size가 1~9 범위를 벗어남 | page=1, size=9로 정규화한 뒤 한 번 다시 조회한다. |
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-007 · 내 자기소개서 목록 조회
 */
export const listCoverLetters = async (
  params?: ListCoverLettersParams,
  options?: Parameters<typeof httpClient>[1]
): Promise<CoverLetterListResponse> => {
  return httpClient<CoverLetterListResponse>(getListCoverLettersUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getCreateCoverLetterUrl = () => {
  return `/cover-letters`;
};

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 새 WRITING 자기소개서 초안을 생성한다.
 *
 * ### 사용 화면
 * 자기소개서 등록
 *
 * ### 호출 시점
 * 사용자가 새 자기소개서 등록을 시작할 때 호출한다.
 *
 * ### 주요 동작
 * 빈 초안을 현재 사용자 소유로 생성하며 입력 데이터는 후속 API-009~011로 저장한다.
 *
 * ### 성공 후 처리
 * 반환된 coverLetterId로 자기소개서 등록 1단계 화면을 연다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-008 · 자기소개서 생성
 */
export const createCoverLetter = async (
  options?: Parameters<typeof httpClient>[1]
): Promise<CreateCoverLetterResponse> => {
  return httpClient<CreateCoverLetterResponse>(getCreateCoverLetterUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getSubmitCoverLetterUrl = (coverLetterId: string) => {
  return `/cover-letters/${coverLetterId}/submit`;
};

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 임시저장된 자기소개서의 필수값을 최종 검증하고 최초 AI 첨삭 Job을 시작한다.
 *
 * ### 사용 화면
 * 자기소개서 등록, 첨삭 진행
 *
 * ### 호출 시점
 * 등록 4단계에서 제출을 확정하거나 최초 첨삭 실패 화면에서 수동 재시도할 때 호출한다.
 *
 * ### 주요 동작
 * WRITING 또는 최초 첨삭 실패 상태의 저장 데이터를 최종 검증한다.
 * 새 Job을 만들거나 동일 최초 첨삭 Job이 진행 중이면 기존 jobId를 반환한다.
 * 200 OK 이후의 AI 처리 실패는 HTTP 오류가 아니라 API-016의 job.state.status=FAILED로 전달된다.
 *
 *
 * ### 성공 후 처리
 * displayStatus=REVIEWING이면 jobId로 API-016 SSE 연결을 시작한다. REVIEWED이면 jobId=null이며 API-012를 조회해 기존 결과 화면으로 전환한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 400 | `VALIDATION_ERROR` | 제출 필수값 누락 또는 길이·범위 위반 | details[].field를 등록 단계에 매핑하고 최초 오류가 있는 단계로 이동한다. |
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 대상 없음 안내 후 목록으로 이동한다. |
 * | 409 | `CONFLICT` | 재첨삭 실패로 기존 성공 버전이 남아 있어 최초 제출 API를 사용할 수 없음 | API-012로 기존 결과를 조회하고 재첨삭은 API-024로 요청한다. |
 * | 409 | `LLM_JOB_ALREADY_RUNNING` | 최초 첨삭 외 다른 AI Job이 진행 중 | 새 요청을 중단하고 제출 화면을 유지하며 자동 재시도하지 않는다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-014 · 자기소개서 제출 및 최초 AI 첨삭 요청
 */
export const submitCoverLetter = async (
  coverLetterId: string,
  options?: Parameters<typeof httpClient>[1]
): Promise<SubmitCoverLetterResponse> => {
  return httpClient<SubmitCoverLetterResponse>(getSubmitCoverLetterUrl(coverLetterId), {
    ...options,
    method: 'POST',
  });
};

export const getGetCoverLetterDetailUrl = (coverLetterId: string) => {
  return `/cover-letters/${coverLetterId}`;
};

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 미완성 WRITING 입력과 자기소개서 상세·첨삭 상태를 공통 구조로 조회한다.
 *
 * ### 사용 화면
 * 자기소개서 목록, 자기소개서 등록, 첨삭 결과
 *
 * ### 호출 시점
 * 목록에서 항목을 열거나 등록·첨삭 화면을 새로고침하고 상태를 복구할 때 호출한다.
 *
 * ### 주요 동작
 * displayStatus에 따라 nullable 등록 데이터, 최신 성공 버전, 진행·실패 Job과 성공한 부분 문항을 조건부 반환한다.
 *
 * ### 성공 후 처리
 * WRITING은 등록 폼을 복구하고 REVIEWING은 API-016에 연결하며 REVIEWED·REVIEW_FAILED는 결과 또는 실패 화면을 구성한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·삭제 | 대상이 없거나 접근할 수 없음을 안내하고 목록으로 이동한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-012 · 자기소개서 상세 조회
 */
export const getCoverLetterDetail = async (
  coverLetterId: string,
  options?: Parameters<typeof httpClient>[1]
): Promise<CoverLetterDetailResponse> => {
  return httpClient<CoverLetterDetailResponse>(getGetCoverLetterDetailUrl(coverLetterId), {
    ...options,
    method: 'GET',
  });
};

export const getDeleteCoverLetterUrl = (coverLetterId: string) => {
  return `/cover-letters/${coverLetterId}`;
};

/**
 * > 인증: 필요 · CSRF: 필요
 *
 * ### 사용 목적
 * 현재 사용자가 소유한 자기소개서를 삭제한다.
 *
 * ### 사용 화면
 * 자기소개서 목록
 *
 * ### 호출 시점
 * 사용자가 목록에서 삭제를 확인할 때 호출한다.
 *
 * ### 주요 동작
 * 자기소개서를 삭제하고 진행 중인 첨삭 Job이 있으면 CANCELED로 전환한다.
 *
 * ### 성공 후 처리
 * 목록에서 항목을 제거하거나 API-007을 다시 조회한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 403 | `CSRF_TOKEN_INVALID` | CSRF 토큰 누락·만료·불일치 | API-003으로 토큰을 재발급하고 원 요청을 한 번 재시도한다. |
 * | 404 | `NOT_FOUND` | 자기소개서 없음·비소유·이미 삭제 | 이미 없는 대상으로 보고 목록에서 제거하며 실패 토스트는 표시하지 않는다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-013 · 자기소개서 삭제
 */
export const deleteCoverLetter = async (
  coverLetterId: string,
  options?: Parameters<typeof httpClient>[1]
): Promise<SuccessResponse> => {
  return httpClient<SuccessResponse>(getDeleteCoverLetterUrl(coverLetterId), {
    ...options,
    method: 'DELETE',
  });
};

export const getStreamCoverLetterReviewStatusesUrl = () => {
  return `/cover-letters/stream`;
};

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 현재 사용자의 자기소개서 첨삭 상태 변경을 하나의 SSE 연결로 수신한다.
 *
 * ### 사용 화면
 * 자기소개서 목록, 첨삭 진행
 *
 * ### 호출 시점
 * 로그인 후 목록·첨삭 진행 화면에서 사용자 단일 EventSource를 만들 때 연결한다.
 *
 * ### 주요 동작
 * cover-letter.review-status.snapshot을 먼저 보내고 이후 cover-letter.review-status.changed 단건 이벤트를 전달한다. 재연결하면 전체 스냅샷으로 복구한다.
 *
 * ### 성공 후 처리
 * 스냅샷과 변경 이벤트를 displayStatus 기준으로 반영한다. 연결 오류는 API-004 인증 갱신 후 재연결하고 반복 실패 시 API-007을 조회한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-030 · 내 자기소개서 첨삭 상태 스트림
 */
export const streamCoverLetterReviewStatuses = async (
  options?: Parameters<typeof httpClient>[1]
): Promise<string> => {
  return httpClient<string>(getStreamCoverLetterReviewStatusesUrl(), {
    ...options,
    method: 'GET',
  });
};
