/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
export interface QuestionRequest {
  /**
     * 자기소개서 문항. 값이 있으면 trim 후 최대 300자
     * @maxLength 300
     * @nullable
     */
  question?: string | null;
  /**
     * 최대 답변 글자 수. 값이 있으면 100 이상 5000 이하
     * @minimum 100
     * @maximum 5000
     * @nullable
     */
  maxAnswerLength?: number | null;
  /**
     * 첨삭 전 원본 답변. 값이 있으면 trim 후 최대 5000자
     * @maxLength 5000
     * @nullable
     */
  originalAnswer?: string | null;
}

export interface SaveQuestionsRequest {
  /** 현재 자기소개서 문항 전체. null 또는 빈 배열이면 기존 문항을 모두 삭제 */
  questions?: QuestionRequest[];
}

export interface SuccessResponse {
  success: boolean;
}

export interface ErrorDetail {
  field: string;
  reason: string;
}

export interface ErrorBody {
  code: string;
  message: string;
  details: ErrorDetail[];
}

export interface ErrorResponse {
  error: ErrorBody;
}

export interface SavePreferencesRequest {
  /**
     * 채용 우대사항. 값이 있으면 trim 후 최대 3000자
     * @maxLength 3000
     * @nullable
     */
  preferences?: string | null;
}

export interface SaveBasicInfoRequest {
  /**
     * 자기소개서 제목. 값이 있으면 trim 후 최대 50자
     * @maxLength 50
     * @nullable
     */
  title?: string | null;
  /**
     * 지원 회사명. 값이 있으면 trim 후 최대 30자
     * @maxLength 30
     * @nullable
     */
  companyName?: string | null;
  /**
     * 지원 직무명. 값이 있으면 trim 후 최대 30자
     * @maxLength 30
     * @nullable
     */
  positionTitle?: string | null;
  /**
     * 채용 공고 URL. 값이 있으면 trim 후 최대 500자
     * @maxLength 500
     * @nullable
     */
  jobPostingUrl?: string | null;
}

export type CoverLetterListItemResponseDisplayStatus = typeof CoverLetterListItemResponseDisplayStatus[keyof typeof CoverLetterListItemResponseDisplayStatus];


export const CoverLetterListItemResponseDisplayStatus = {
  WRITING: 'WRITING',
  REVIEWING: 'REVIEWING',
  REVIEWED: 'REVIEWED',
  REVIEW_FAILED: 'REVIEW_FAILED',
} as const;

export interface CoverLetterListItemResponse {
  id: string;
  /** @nullable */
  title: string | null;
  /** @nullable */
  companyName: string | null;
  /** @nullable */
  positionTitle: string | null;
  displayStatus: CoverLetterListItemResponseDisplayStatus;
  createdAt: string;
  /** @nullable */
  latestReviewedVersionId: string | null;
}

export interface CoverLetterListResponse {
  items: CoverLetterListItemResponse[];
  page: number;
  size: number;
  totalItems: number;
  totalPages: number;
}

export interface CreateCoverLetterResponse {
  id: string;
}

export type SubmitCoverLetterResponseDisplayStatus = typeof SubmitCoverLetterResponseDisplayStatus[keyof typeof SubmitCoverLetterResponseDisplayStatus];


export const SubmitCoverLetterResponseDisplayStatus = {
  WRITING: 'WRITING',
  REVIEWING: 'REVIEWING',
  REVIEWED: 'REVIEWED',
  REVIEW_FAILED: 'REVIEW_FAILED',
} as const;

export interface SubmitCoverLetterResponse {
  displayStatus: SubmitCoverLetterResponseDisplayStatus;
  /** @nullable */
  jobId: string | null;
}

export type CoverLetterDetailCoverLetterResponseDisplayStatus = typeof CoverLetterDetailCoverLetterResponseDisplayStatus[keyof typeof CoverLetterDetailCoverLetterResponseDisplayStatus];


export const CoverLetterDetailCoverLetterResponseDisplayStatus = {
  WRITING: 'WRITING',
  REVIEWING: 'REVIEWING',
  REVIEWED: 'REVIEWED',
  REVIEW_FAILED: 'REVIEW_FAILED',
} as const;

export interface CoverLetterDetailCoverLetterResponse {
  id: string;
  /** @nullable */
  title: string | null;
  /** @nullable */
  companyName: string | null;
  /** @nullable */
  positionTitle: string | null;
  /** @nullable */
  jobPostingUrl: string | null;
  /** @nullable */
  preferences: string | null;
  displayStatus: CoverLetterDetailCoverLetterResponseDisplayStatus;
}

export interface CoverLetterDetailReviewVersionResponse {
  id: string;
  version: string;
  isLatest: boolean;
  /** @nullable */
  requestInstruction: string | null;
  createdAt: string;
}

export type ReviewJobResponseStatus = typeof ReviewJobResponseStatus[keyof typeof ReviewJobResponseStatus];


export const ReviewJobResponseStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
} as const;

export interface CoverLetterDetailProgressResponse {
  current: number;
  total: number;
  message: string;
}

export interface CoverLetterDetailJobErrorResponse {
  code: string;
  message: string;
}

export interface ReviewJobResponse {
  id: string;
  status: ReviewJobResponseStatus;
  progress: CoverLetterDetailProgressResponse;
  error: CoverLetterDetailJobErrorResponse | null;
}

export interface QuestionResponse {
  /** @nullable */
  questionResultId: string | null;
  questionId: string;
  order: number;
  /** @nullable */
  question: string | null;
  /** @nullable */
  maxAnswerLength: number | null;
  /** @nullable */
  originalAnswer: string | null;
  /** @nullable */
  originalAnswerLength: number | null;
  /** @nullable */
  aiReport: string | null;
  /** @nullable */
  rewrittenAnswer: string | null;
  /** @nullable */
  rewrittenAnswerLength: number | null;
  /** @nullable */
  finalAnswer: string | null;
  /** @nullable */
  finalAnswerLength: number | null;
}

export interface CoverLetterDetailResponse {
  coverLetter: CoverLetterDetailCoverLetterResponse;
  reviewVersion: CoverLetterDetailReviewVersionResponse | null;
  reviewJob: ReviewJobResponse | null;
  questions: QuestionResponse[];
}

export type ListCoverLettersParams = {
page?: number;
size?: number;
};
