/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
import { httpClient } from '@/shared/api/httpClient';
import type {
  LlmJobStateResponseStatus,
  LlmJobProgressResponse,
  ResultRefResponse,
  LlmJobErrorResponse,
  LlmJobStateResponse,
  ErrorDetail,
  ErrorBody,
  ErrorResponse,
} from './types';

export const getGetLlmJobStatusUrl = (jobId: string) => {
  return `/llm-jobs/${jobId}`;
};

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 비동기 LLM Job의 현재 상태를 조회해 SSE 실패 시 최종 상태를 복구한다.
 *
 * ### 사용 화면
 * 첨삭 진행, 키워드 분석, AI 면접
 *
 * ### 호출 시점
 * API-016 연결·재연결 실패, 이벤트 유실 또는 새로고침 시 polling fallback으로 호출한다.
 *
 * ### 주요 동작
 * PENDING·PROCESSING 진행률과 COMPLETED·FAILED·CANCELED 종료 상태를 반환한다. status=FAILED는 HTTP 오류가 아닌 200 응답이다.
 *
 * ### 성공 후 처리
 * 종료 상태에서 polling을 멈추고 resultRef에 맞는 도메인 조회 또는 error.code 기반 실패 처리를 수행한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | Job 없음, 비소유 또는 삭제된 자기소개서에 연결된 Job | polling을 종료하고 원래 도메인 화면 또는 목록을 다시 조회한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-015 · Job 상태 조회
 */
export const getLlmJobStatus = async (
  jobId: string,
  options?: Parameters<typeof httpClient>[1]
): Promise<LlmJobStateResponse> => {
  return httpClient<LlmJobStateResponse>(getGetLlmJobStatusUrl(jobId), {
    ...options,
    method: 'GET',
  });
};

export const getStreamLlmJobEventsUrl = (jobId: string) => {
  return `/llm-jobs/${jobId}/stream`;
};

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 첨삭·키워드 분석·AI 면접 Job의 상태와 도메인별 중간 결과를 하나의 SSE 연결로 수신한다.
 *
 * ### 사용 화면
 * 첨삭 진행, 키워드 분석, AI 면접
 *
 * ### 호출 시점
 * Job 시작 API가 반환한 jobId로 진행 상태를 구독할 때 연결한다.
 *
 * ### 주요 동작
 * job.state 이벤트로 최초 상태, 진행률과 종료 상태를 전달한다.
 * 첨삭 문항은 review.questions, 면접 피드백은 interview.feedback.delta 이벤트로 전달한다.
 * job.state.status=FAILED는 정상 SSE 연결에서 받은 비동기 작업 결과이며 HTTP ErrorResponse가 아니다.
 *
 *
 * ### 성공 후 처리
 * 서버가 최종 job.state와 도메인별 후속 이벤트 전송을 마친 뒤 연결을 종료한다. 클라이언트는 terminal 상태에 따라 API별 결과 조회 또는 실패 처리를 수행한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | Job 없음, 접근 불가 또는 삭제된 자기소개서에 연결된 Job | 스트림 재연결을 중단하고 API-015 또는 도메인 조회로 최종 상태를 확인한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-016 · Job 스트림
 */
export const streamLlmJobEvents = async (
  jobId: string,
  options?: Parameters<typeof httpClient>[1]
): Promise<string> => {
  return httpClient<string>(getStreamLlmJobEventsUrl(jobId), {
    ...options,
    method: 'GET',
  });
};
