/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
import { httpClient } from '@/shared/api/httpClient';
import type {
  LlmJobStateResponseStatus,
  LlmJobProgressResponse,
  ResultRefResponse,
  LlmJobErrorResponse,
  LlmJobStateResponse,
  ErrorDetail,
  ErrorBody,
  ErrorResponse,
} from './types';

export const getGetLlmJobStatusUrl = (jobId: string) => {
  return `/llm-jobs/${jobId}`;
};

/**
 * > 인증: 필요 · CSRF: 불필요
 *
 * ### 사용 목적
 * 비동기 LLM Job의 현재 상태를 조회해 SSE 실패 시 최종 상태를 복구한다.
 *
 * ### 사용 화면
 * 첨삭 진행, 키워드 분석, AI 면접
 *
 * ### 호출 시점
 * API-016 연결·재연결 실패, 이벤트 유실 또는 새로고침 시 polling fallback으로 호출한다.
 *
 * ### 주요 동작
 * PENDING·PROCESSING 진행률과 COMPLETED·FAILED·CANCELED 종료 상태를 반환한다. status=FAILED는 HTTP 오류가 아닌 200 응답이다.
 *
 * ### 성공 후 처리
 * 종료 상태에서 polling을 멈추고 resultRef에 맞는 도메인 조회 또는 error.code 기반 실패 처리를 수행한다.
 *
 * ### 오류
 * | HTTP | 오류 코드 | 발생 조건 | 처리 |
 * |---:|---|---|---|
 * | 401 | `UNAUTHORIZED` | access token이 없거나 만료됨 | API-004로 토큰을 한 번 갱신하고 원 요청을 한 번 재시도한다. 실패하면 로그인 화면으로 이동한다. |
 * | 404 | `NOT_FOUND` | Job 없음, 비소유 또는 삭제된 자기소개서에 연결된 Job | polling을 종료하고 원래 도메인 화면 또는 목록을 다시 조회한다. |
 * | 500 | `INTERNAL_ERROR` | 예상하지 못한 서버 오류 | 공통 일시 오류를 표시하며 상태 변경 요청은 자동 재전송하지 않는다. |
 * @summary API-015 · Job 상태 조회
 */
export const getLlmJobStatus = async (
  jobId: string,
  options?: Parameters<typeof httpClient>[1]
): Promise<LlmJobStateResponse> => {
  return httpClient<LlmJobStateResponse>(getGetLlmJobStatusUrl(jobId), {
    ...options,
    method: 'GET',
  });
};
