/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rewrite API
 * API 번호, 사용 화면, 호출 흐름과 오류 조건을 확인하는 Rewrite 백엔드 핵심 API 문서
 * OpenAPI spec version: v1
 */
export type LlmJobStateResponseStatus = typeof LlmJobStateResponseStatus[keyof typeof LlmJobStateResponseStatus];


export const LlmJobStateResponseStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
} as const;

export interface ProgressResponse {
  current?: number;
  total?: number;
  message?: string;
}

export interface ResultRefResponse {
  type?: string;
  id?: string;
}

export interface ErrorDetail {
  field?: string;
  reason?: string;
}

export interface ErrorBody {
  code?: string;
  message?: string;
  details?: ErrorDetail[];
}

export interface ErrorResponse {
  error?: ErrorBody;
}

export interface LlmJobStateResponse {
  status?: LlmJobStateResponseStatus;
  progress?: ProgressResponse;
  resultRef?: ResultRefResponse;
  error?: ErrorResponse;
}
